services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

  posting-service:
    image: vinhopenfabric/mock-posting-service:latest
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=/data/transactions.db
    volumes:
      - ./data:/data   # Use local folder instead of named volume

  transaction-service:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTING_SERVICE_URL=http://posting-service:8080
    depends_on:
      - redis
      - posting-service
    volumes:
      - .:/app
    command: python run.py
